language: objective-c
osx_image: xcode7.3
before_install:
  - brew install docker
  - brew install docker-machine
  - brew cask install virtualbox
  - docker-machine create --driver virtualbox --virtualbox-no-vtx-check default
script:
  - git clone https://github.com/ethereum/go-ethereum
  - cd go-ethereum
  - eval $(docker-machine env default)
  - make geth-ios
